services:
  slack-bot:
    build: .
    volumes:
      - ./.env:/app/.env:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./storage:/app/storage
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    init: true 
