application:
  log_level: INFO

  storage:
    "勤怠":
      path: ./storage/local/kintai
    "有休":
      path: ./storage/local/yukyu
    "BACKUP":
      path: ./storage/local/backup
    "LOG":
      path: ./logs
